<a href="https://colab.research.google.com/github/PrayushPai/Deep-Learning-Projects/blob/main/Cars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('Cars.csv')
df.head()

Car ID         make fuel-type  ... city-mpg highway-mpg  price
0       1  alfa-romero       gas  ...       21          27  13495
1       2  alfa-romero       gas  ...       21          27  16500
2       3  alfa-romero       gas  ...       19          26  16500
3       4         audi       gas  ...       24          30  13950
4       5         audi       gas  ...       18          22  17450

[5 rows x 23 columns]

In [ ]:
df.shape


(195, 23)

In [ ]:
df.nunique()


Car ID               195
make                  21
fuel-type              2
aspiration             2
num-of-doors           2
body-style             5
drive-wheels           3
engine-location        2
wheel-base            50
length                71
width                 41
height                46
curb-weight          166
num-of-cylinders       6
engine-size           40
bore                  38
stroke                36
compression-ratio     32
horsepower            57
peak-rpm              22
city-mpg              29
highway-mpg           30
price                180
dtype: int64

In [ ]:
df_n = df.select_dtypes(include = ['int64','float64'])
df_n

Car ID  wheel-base  length  width  ...  peak-rpm  city-mpg  highway-mpg  price
0         1        88.6   168.8   64.1  ...      5000        21           27  13495
1         2        88.6   168.8   64.1  ...      5000        21           27  16500
2         3        94.5   171.2   65.5  ...      5000        19           26  16500
3         4        99.8   176.6   66.2  ...      5500        24           30  13950
4         5        99.4   176.6   66.4  ...      5500        18           22  17450
..      ...         ...     ...    ...  ...       ...       ...          ...    ...
190     191       109.1   188.8   68.9  ...      5400        23           28  16845
191     192       109.1   188.8   68.8  ...      5300        19           25  19045
192     193       109.1   188.8   68.9  ...      5500        18           23  21485
193     194       109.1   188.8   68.9  ...      4800        26           27  22470
194     195       109.1   188.8   68.9  ...      5400        19           25  22625

[195 rows x 15 columns]

In [ ]:
x = df_n.iloc[:,1:-1].values



In [ ]:
y = df_n.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)


In [ ]:
print(x_train.shape)
print(x_test.shape)

(146, 13)
(49, 13)


In [ ]:
x_train[0]

array([9.720e+01, 1.734e+02, 6.520e+01, 5.470e+01, 2.324e+03, 1.200e+02,
       3.330e+00, 3.470e+00, 8.500e+00, 9.700e+01, 5.200e+03, 2.700e+01,
       3.400e+01])

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x)
y_pred

array([12675.61897943, 12675.61897943, 17989.08791674, 11430.63706699,
       14807.09377159, 14630.48812865, 17587.28132909, 17676.56852355,
       17580.96453608, 12971.3811342 , 12971.3811342 , 17150.6000351 ,
       17195.24363233, 17837.95998818, 28080.24326412, 27741.07227455,
       29759.79065309,   678.16563509,  6335.90072852,  6281.19788957,
        5315.21900776,  6257.38342196,  7558.61825397,  6260.18482216,
        6278.04226105,  6278.04226105,  7538.69200467, 12306.05737057,
       13897.45170682,  3397.59569402,  7436.21683177,  5247.40471107,
        7365.67516291,  7378.6623912 ,  7818.87990527,  9311.21522886,
        9971.09685237, 10014.11704606, 10084.13677166,  9093.69348806,
       10233.35851874,  9439.63074735,  6817.3096528 ,  9788.27664989,
       30079.27806751, 30079.27806751, 47695.00887938,  4743.09687001,
        6667.84370056,  6671.9022094 ,  6483.6925262 ,  6432.44398784,
       10098.36560064, 10758.22929093, 10098.36560064, 10758.22929093,
      

In [ ]:
y_train

array([ 8949, 13415,  6692,  6855, 17950, 12945, 10198,  7738,  7999,
        6575,  7788,  9980, 10595,  9989, 36880,  7395,  9495, 11259,
       16630,  7349, 13499, 12290,  6938, 21485, 30760,  8921, 17199,
        9538, 36000, 19045, 16845, 28176, 16500, 18344,  5572,  7957,
       11048, 16925, 19699,  9959, 18420, 11595,  7898,  7053,  9549,
       17075,  8238, 16515,  6695, 13495, 13499,  8778, 14399, 34184,
        8013, 10345,  5389,  6795,  6095,  6849, 24565, 10698,  6229,
       13845,  7126,  5572, 41315,  6989, 15580,  8845, 11900, 14869,
       13950,  8921, 22470, 18150, 17710, 16503, 12629,  6649, 37028,
        8449, 11248,  9258,  8249, 16558, 20970, 32528, 12440,  7295,
       11245, 35056, 16500, 34028,  9639,  6785, 16900,  7775, 15998,
        5151,  8845,  9960,  8495,  8058,  5118,  7295, 12964,  6692,
        8358,  5399, 17669, 18620, 22625,  6529,  6488,  8495,  7198,
        6479, 18399,  5499,  8189,  7609,  7898, 18950,  7689, 14489,
        7609,  9988,

In [ ]:
import numpy as np

from sklearn.metrics import mean_squared_error,r2_score
mean_squared_error(y_train,y_pred)


ValueError: ignored

In [ ]:
error = np.subtract(y_pred,y_train)
sq_error = np.square(error) # To remove -ve values
m_sq_error = np.mean(sq_error)
m_sq_error

ValueError: ignored